feat/updated examples with server work dir arg
ansys/pyworkbench-examples pull request #66
Opened 2024-08-21 07:39 UTC by vnamdeo

@franknli Could you please review these changes and approve it accordingly. Thanks!

These examples have following changes:

1. Specified "release" and "server_workdir" arguments to showcase to the user (though these options are default)
2. Specified "upload_file_from_example_repo" API to download and upload input files from example repo to server working directory. With the usage of this API, we can track the issues if it's occurring with the future code changes.

2024-08-21 16:57 UTC, franknli commented
> @franknli Could you please review these changes and approve it accordingly. Thanks!
> 
> These examples have following changes:
> 
> 1. Specified "release" and "server_workdir" arguments to showcase to the user (though these options are default)
> 2. Specified "upload_file_from_example_repo" API to download and upload input files from example repo to server working directory. With the usage of this API, we can track the issues if it's occurring with the future code changes.

@vnamdeo Using "upload_file_from_example_repo" is definitely a nice improvement! However, I am not sure about specifying release and server_workdir, per our private chat.

2024-08-21 17:17 UTC, vnamdeo commented
> > @franknli Could you please review these changes and approve it accordingly. Thanks!
> > These examples have following changes:
> > 
> > 1. Specified "release" and "server_workdir" arguments to showcase to the user (though these options are default)
> > 2. Specified "upload_file_from_example_repo" API to download and upload input files from example repo to server working directory. With the usage of this API, we can track the issues if it's occurring with the future code changes.
> 
> @vnamdeo Using "upload_file_from_example_repo" is definitely a nice improvement! However, I am not sure about specifying release and server_workdir, per our private chat.

@franknli I have modified these examples as per our discussion. Please take a look for the further approval. Thanks!

2024-08-21 17:28 UTC, franknli commented
> > @franknli Could you please review these changes and approve it accordingly. Thanks!
> > These examples have following changes:
> > 
> > 1. Specified "release" and "server_workdir" arguments to showcase to the user (though these options are default)
> > 2. Specified "upload_file_from_example_repo" API to download and upload input files from example repo to server working directory. With the usage of this API, we can track the issues if it's occurring with the future code changes.
> 
> @vnamdeo Using "upload_file_from_example_repo" is definitely a nice improvement! However, I am not sure about specifying release and server_workdir, per our private chat.

Sure. See my review comments!

Also, since we are now uploading these data files from example_repo, can we remove them from this repo - all the wbpz/agdb/cdb subdirectories can now be removed?

2024-08-22 09:34 UTC, vnamdeo commented
> > > @franknli Could you please review these changes and approve it accordingly. Thanks!
> > > These examples have following changes:
> > > 
> > > 1. Specified "release" and "server_workdir" arguments to showcase to the user (though these options are default)
> > > 2. Specified "upload_file_from_example_repo" API to download and upload input files from example repo to server working directory. With the usage of this API, we can track the issues if it's occurring with the future code changes.
> > 
> > 
> > @vnamdeo Using "upload_file_from_example_repo" is definitely a nice improvement! However, I am not sure about specifying release and server_workdir, per our private chat.
> 
> Sure. See my review comments!
> 
> Also, since we are now uploading these data files from example_repo, can we remove them from this repo - all the wbpz/agdb/cdb subdirectories can now be removed?

@franknli Thanks for the review. I have removed subdirectories which are not required. Thanks!

2024-08-23 14:23 UTC, abhishekchitwar approved these changes

2024-08-23 14:39 UTC, franknli requested changes

2024-08-23 16:04 UTC, vnamdeo commented on examples/cooled-turbine-blade/main.py
> +wb.upload_file(str(scripts / "cooled_turbine_blade.py"))
Done @franknli

2024-08-23 16:04 UTC, vnamdeo commented on examples/cyclic-symmetry-analysis/main.py
> +wb.upload_file(str(scripts / "cyclic_symmetry_analysis.py"))
Done @franknli

2024-08-23 16:48 UTC, franknli approved these changes
Looks great! Thanks.

2024-08-23 18:47 UTC, merged